import assert from 'node:assert/strict';
import {build} from 'esbuild';import {rm} from 'node:fs/promises';import * as THREE from 'three';
const file='scripts/.combat-effects-check.mjs',original=globalThis.document;
try{
 globalThis.document={createElement:()=>({width:128,height:128,getContext:()=>({beginPath(){},ellipse(){},fill(){}})})};await build({entryPoints:['client/src/game/CombatEffects.ts'],outfile:file,bundle:true,format:'esm',packages:'external'});const {CombatEffects}=await import('./.combat-effects-check.mjs');
 const scene=new THREE.Scene(),wall=new THREE.Mesh(new THREE.BoxGeometry(4,4,.2));wall.position.set(0,2,-1);wall.updateMatrixWorld();scene.add(wall);const effects=new CombatEffects(scene,{floorAt:()=>0},[wall]);const before=scene.children.length;
 effects.blood(new THREE.Vector3(0,1,0),new THREE.Vector3(0,0,-1),true);assert.equal(scene.children.length,before+2,'fatal hit adds wall splatter and floor stain');effects.update(0);assert.equal(scene.children.find(m=>m instanceof THREE.Points).geometry.drawRange.count,70,'fatal/corpse hit uses seventy blood droplets');effects.blood(new THREE.Vector3(0,.2,0),new THREE.Vector3(0,-1,0),true,true);effects.update(0);assert.equal(scene.children.find(m=>m instanceof THREE.Points).geometry.drawRange.count,170,'corpse hit adds one hundred blood droplets');const gun=new THREE.Group();scene.add(gun);effects.shot(gun);assert.ok(scene.children.some(m=>m instanceof THREE.Mesh&&m.geometry.type==='CylinderGeometry'),'brass ejected');
 for(let i=0;i<90;i++)effects.update(1/60);const points=scene.children.find(m=>m instanceof THREE.Points);assert.equal(points.geometry.drawRange.count,0,'blood/smoke particles expire');effects.reset();assert.equal(scene.children.filter(m=>m.userData.effect).length,1,'round reset clears stains and casings while retaining particle buffer');console.log('PASS: blood spray, floor/wall decals, brass/smoke lifecycle and round cleanup.');
}finally{globalThis.document=original;await rm(file,{force:true})}
